/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.CardLayout;

/**
 *
 * @author User
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        shippingButton.setVisible(false);
        trackingButton.setVisible(false);
        distributeButton.setVisible(false);
        managerButton.setVisible(false);
        trainsferStationButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        shippingButton = new javax.swing.JButton();
        trackingButton = new javax.swing.JButton();
        distributeButton = new javax.swing.JButton();
        managerButton = new javax.swing.JButton();
        trainsferStationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        shippingButton.setText("shippingPanel");
        shippingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingButtonActionPerformed(evt);
            }
        });
        topPanel.add(shippingButton);

        trackingButton.setText("trackingPanel");
        trackingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingButtonActionPerformed(evt);
            }
        });
        topPanel.add(trackingButton);

        distributeButton.setText("distributePanel");
        distributeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributeButtonActionPerformed(evt);
            }
        });
        topPanel.add(distributeButton);

        managerButton.setText("managerPanel");
        managerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonActionPerformed(evt);
            }
        });
        topPanel.add(managerButton);

        trainsferStationButton.setText("transferstationPanel");
        trainsferStationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainsferStationButtonActionPerformed(evt);
            }
        });
        topPanel.add(trainsferStationButton);

        logoutButton.setText("logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        topPanel.add(logoutButton);

        splitPanel.setTopComponent(topPanel);

        bottomPanel.setLayout(new java.awt.CardLayout());
        splitPanel.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shippingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingButtonActionPerformed
        ShippingPanel shippingPanel = new ShippingPanel(); // create new panel
        splitPanel.setBottomComponent(shippingPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_shippingButtonActionPerformed

    private void trackingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingButtonActionPerformed
        TrackingPanel trackingPanel = new TrackingPanel();
        splitPanel.setBottomComponent(trackingPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);// TODO add your handling code here:
    }//GEN-LAST:event_trackingButtonActionPerformed

    private void distributeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributeButtonActionPerformed
        distributePanel distributePanel = new distributePanel();
        splitPanel.setBottomComponent(distributePanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);// TODO add your handling code here:
    }//GEN-LAST:event_distributeButtonActionPerformed

    private void managerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonActionPerformed
        managerPanel managerPanel = new managerPanel();
        splitPanel.setBottomComponent(managerPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);// TODO add your handling code here:
    }//GEN-LAST:event_managerButtonActionPerformed

    private void trainsferStationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainsferStationButtonActionPerformed
        transferStationPanel transferStationPanel = new transferStationPanel();
        splitPanel.setBottomComponent(transferStationPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);// TODO add your handling code here:
    }//GEN-LAST:event_trainsferStationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginFrame l = new LoginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    public void setButton(String s) {
        if (s.equals("customer")) {
            shippingButton.setVisible(true);
            trackingButton.setVisible(true);
        } else if (s.equals("distribute")) {
            distributeButton.setVisible(true);
        } else if (s.equals("transfer")) {
            trainsferStationButton.setVisible(true);
        } else if (s.equals("manager")) {
            managerButton.setVisible(true);
        } else {
            managerButton.setVisible(true);
            trainsferStationButton.setVisible(true);
            distributeButton.setVisible(true);
            shippingButton.setVisible(true);
            trackingButton.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton distributeButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton managerButton;
    private javax.swing.JButton shippingButton;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton trackingButton;
    private javax.swing.JButton trainsferStationButton;
    // End of variables declaration//GEN-END:variables
}
