package src;

import connect.util.DbUtil;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.NumberDirectory;
import model.Shipment;
import model.ShipmentDirectory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author User
 */
public class ShippingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShippingPanel
     */
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    
    public String packageStatus (){
        String gas = null;
        String liquid = null;
        String solid = null;
        String flame = null;
        String fragile = null;
        String toxic = null;
        
        if (gasBox.isSelected()){
            gas = "gas";
        }
        if (liquidBox.isSelected()){
            liquid = "liquid";
        }
        if (solidBox.isSelected()){
            solid = "solid";
        }
        if (flammableBox.isSelected()){
            flame = "flammable";
        }
        if (fragileBox.isSelected()){
            fragile = "fragile";
        }
        if (toxicBox.isSelected()){
            toxic = "toxic";
        }
        return gas+liquid+solid+flame+toxic;
    }
    public ShippingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        deProvinceLabel = new javax.swing.JLabel();
        deCityLabel = new javax.swing.JLabel();
        deRegionLabel = new javax.swing.JLabel();
        destinationTitleLabel = new javax.swing.JLabel();
        deProvinceField = new javax.swing.JTextField();
        deCityField = new javax.swing.JTextField();
        deRegionField = new javax.swing.JTextField();
        deAddressLabel = new javax.swing.JLabel();
        deAddressField = new javax.swing.JTextField();
        phoneNumLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneNumField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        shipperInfoLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        regionField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        regionLabel = new javax.swing.JLabel();
        provinceField = new javax.swing.JTextField();
        packageTitleField = new javax.swing.JLabel();
        weighLabel = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        kgLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        solidBox = new javax.swing.JCheckBox();
        liquidBox = new javax.swing.JCheckBox();
        gasBox = new javax.swing.JCheckBox();
        fragileBox = new javax.swing.JCheckBox();
        flammableBox = new javax.swing.JCheckBox();
        toxicBox = new javax.swing.JCheckBox();
        shipperNameLabel = new javax.swing.JLabel();
        shipperNameField = new javax.swing.JTextField();
        ShipperIDLabel = new javax.swing.JLabel();
        shipperIDField = new javax.swing.JTextField();
        recieverNameLabel = new javax.swing.JLabel();
        rePhoneNumLabel = new javax.swing.JLabel();
        recieverNameField = new javax.swing.JTextField();
        rePhoneNumField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        reEmailLabel = new javax.swing.JLabel();
        reEmailField = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 727));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("New Shipping");

        deProvinceLabel.setText("Province");

        deCityLabel.setText("City");

        deRegionLabel.setText("Region");

        destinationTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationTitleLabel.setText("Destination:");

        deAddressLabel.setText("Address");

        phoneNumLabel.setText("Phone Number");

        emailLabel.setText("Email Address");

        shipperInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shipperInfoLabel.setText("Shipper Info");

        addressLabel.setText("Address");

        provinceLabel.setText("Province");

        cityLabel.setText("City");

        regionLabel.setText("Region");

        packageTitleField.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        packageTitleField.setText("Package properties");

        weighLabel.setText("Weight");

        kgLabel.setText("kg");

        statusLabel.setText("Status");

        solidBox.setText("Solid");

        liquidBox.setText("Liquid");

        gasBox.setText("Gas");

        fragileBox.setText("fragile");

        flammableBox.setText("flammable");

        toxicBox.setText("toxic");

        shipperNameLabel.setText("Shipper Name");

        ShipperIDLabel.setText("Shipper ID");

        recieverNameLabel.setText("Reciever Name");

        rePhoneNumLabel.setText("Phone Number");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        reEmailLabel.setText("Email");

        dataLabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(packageTitleField)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(weighLabel)
                                .addGap(18, 18, 18)
                                .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kgLabel)
                                .addGap(57, 57, 57)
                                .addComponent(statusLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(solidBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(liquidBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fragileBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(flammableBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(toxicBox))))
                            .addComponent(destinationTitleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(deProvinceLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(deProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(deCityLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(deCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(deAddressLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(deAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(63, 63, 63)
                                        .addComponent(deRegionLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(deRegionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(dataLabel)
                                                .addGap(44, 44, 44)
                                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(rePhoneNumLabel)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rePhoneNumField))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(recieverNameLabel)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(recieverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(41, 41, 41)
                                                .addComponent(reEmailLabel)))
                                        .addGap(18, 18, 18)
                                        .addComponent(reEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(provinceLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(cityLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(regionLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(regionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNumLabel)
                                            .addComponent(emailLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(emailField)
                                            .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(shipperNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(shipperNameLabel))
                                        .addGap(18, 18, 18)
                                        .addComponent(ShipperIDLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(shipperIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(shipperInfoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(titleLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(submitButton)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(shipperInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipperNameLabel)
                    .addComponent(shipperNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShipperIDLabel)
                    .addComponent(shipperIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumLabel)
                    .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinceLabel)
                    .addComponent(cityLabel)
                    .addComponent(regionLabel)
                    .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(packageTitleField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weighLabel)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgLabel)
                    .addComponent(statusLabel)
                    .addComponent(solidBox)
                    .addComponent(liquidBox)
                    .addComponent(gasBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fragileBox)
                    .addComponent(flammableBox)
                    .addComponent(toxicBox))
                .addGap(18, 18, 18)
                .addComponent(destinationTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deProvinceLabel)
                    .addComponent(deCityLabel)
                    .addComponent(deRegionLabel)
                    .addComponent(deProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deRegionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deAddressLabel)
                    .addComponent(deAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recieverNameLabel)
                    .addComponent(recieverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePhoneNumLabel)
                    .addComponent(rePhoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reEmailLabel)
                    .addComponent(reEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            // TODO add your handling code here:
            Shipment ship = new Shipment();
            ship.setPhoneNum(Integer.parseInt(phoneNumField.getText()));
            ship.setTrackingNum(NumberDirectory.getInstance().generateRefNum());
            ship.setDesAddress(deAddressField.getText()+','+deRegionField.getText()+','+deCityField.getText()+','+deProvinceField.getText());
            ship.setStartAddress(addressField.getText()+','+regionField.getText()+','+cityField.getText()+','+provinceField.getText());
            ship.setShipEmail(emailField.getText());
            ship.setRecipientsEmail(reEmailField.getText());
            ship.setShipper(shipperNameField.getText());
            ship.setRecipients(recieverNameField.getText());
            ship.setStartDate( format.parse(dateField.getText()));
            ship.setPackageInfo(packageStatus());
            
            ShipmentDirectory.getInstance().addShipment(ship);
            DbUtil.getInstance().addShipmentToShipTable(ship);
            JOptionPane.showMessageDialog(this, "Shipment created!");
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(ShippingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShipperIDLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField deAddressField;
    private javax.swing.JLabel deAddressLabel;
    private javax.swing.JTextField deCityField;
    private javax.swing.JLabel deCityLabel;
    private javax.swing.JTextField deProvinceField;
    private javax.swing.JLabel deProvinceLabel;
    private javax.swing.JTextField deRegionField;
    private javax.swing.JLabel deRegionLabel;
    private javax.swing.JLabel destinationTitleLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JCheckBox flammableBox;
    private javax.swing.JCheckBox fragileBox;
    private javax.swing.JCheckBox gasBox;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JCheckBox liquidBox;
    private javax.swing.JLabel packageTitleField;
    private javax.swing.JTextField phoneNumField;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JTextField provinceField;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JTextField reEmailField;
    private javax.swing.JLabel reEmailLabel;
    private javax.swing.JTextField rePhoneNumField;
    private javax.swing.JLabel rePhoneNumLabel;
    private javax.swing.JTextField recieverNameField;
    private javax.swing.JLabel recieverNameLabel;
    private javax.swing.JTextField regionField;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JTextField shipperIDField;
    private javax.swing.JLabel shipperInfoLabel;
    private javax.swing.JTextField shipperNameField;
    private javax.swing.JLabel shipperNameLabel;
    private javax.swing.JCheckBox solidBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JCheckBox toxicBox;
    private javax.swing.JLabel weighLabel;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
